name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build ./app --file app/Dockerfile --tag docker.pkg.github.com/frutik/aio-py/aio-test:latest
    - name: log in
      run: docker login -u frutik -p GITHUB_TOKEN docker.pkg.github.com
    - name: push
      run: docker push docker.pkg.github.com/frutik/aio-py/aio-test:latest
   
